// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmrpiE4054GY43v3twjGN27yzWADLNUKM',
    appId: '1:907538546027:web:33a15b703d0c3b207fa02e',
    messagingSenderId: '907538546027',
    projectId: 'kesehatan-1dbad',
    authDomain: 'kesehatan-1dbad.firebaseapp.com',
    storageBucket: 'kesehatan-1dbad.firebasestorage.app',
    databaseURL: 'https://kesehatan-1dbad-default-rtdb.firebaseio.com', // <-- TAMBAHKAN INI
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwU7Et0GrgbGMpfsBNEcjssAZwE0ySKNc',
    appId: '1:907538546027:android:2962ab6842edb9c47fa02e',
    messagingSenderId: '907538546027',
    projectId: 'kesehatan-1dbad',
    storageBucket: 'kesehatan-1dbad.firebasestorage.app',
    databaseURL: 'https://kesehatan-1dbad-default-rtdb.firebaseio.com', // <-- TAMBAHKAN INI
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZ3O0uXLYM3YjM3HmprujNyLTDMj0v6Y',
    appId: '1:907538546027:ios:6a82c9d5c11538277fa02e',
    messagingSenderId: '907538546027',
    projectId: 'kesehatan-1dbad',
    storageBucket: 'kesehatan-1dbad.firebasestorage.app',
    iosBundleId: 'com.example.hitung',
    databaseURL: 'https://kesehatan-1dbad-default-rtdb.firebaseio.com', // <-- TAMBAHKAN INI
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZ3O0uXLYM3YjM3HmprujNyLTDMj0v6Y',
    appId: '1:907538546027:ios:6a82c9d5c11538277fa02e',
    messagingSenderId: '907538546027',
    projectId: 'kesehatan-1dbad',
    storageBucket: 'kesehatan-1dbad.firebasestorage.app',
    iosBundleId: 'com.example.hitung',
    databaseURL: 'https://kesehatan-1dbad-default-rtdb.firebaseio.com', // <-- TAMBAHKAN INI
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmrpiE4054GY43v3twjGN27yzWADLNUKM',
    appId: '1:907538546027:web:f5b08fb38fe17b477fa02e',
    messagingSenderId: '907538546027',
    projectId: 'kesehatan-1dbad',
    authDomain: 'kesehatan-1dbad.firebaseapp.com',
    storageBucket: 'kesehatan-1dbad.firebasestorage.app',
    databaseURL: 'https://kesehatan-1dbad-default-rtdb.firebaseio.com', // <-- TAMBAHKAN INI
  );
}